modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "ISC"

[[mods]]
modId = "keymap"
version = "${version}"
displayName = "keymap"
authors = "Einjerjar, SettingDust"
description = '''
keymap
'''
logoFile = "icon.png"

[[dependencies.keymap]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keymap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "keymap-common.mixins.json"
